name: "📚 Documentation"
description: "Template for documentation updates"
title: "📚 [DOCS] - <brief description>"
labels: [
  "documentation"
]
body:
  - type: dropdown
    id: doc-type
    attributes:
      label: "Documentation Type"
      options:
        - Pattern Implementation Guide
        - Problem Solution Explanation
        - README Update
        - Performance Analysis
        - Language-Specific Notes
    validations:
      required: true

  - type: textarea
    id: proposed-changes
    attributes:
      label: "Proposed Changes"
      description: "What documentation needs to be added/updated?"
      placeholder: "Describe the documentation changes..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Why is this documentation needed?"
    validations:
      required: true

  - type: input
    id: related-issues
    attributes:
      label: "Related Issues"
      description: "Link any related issues or PRs"
      placeholder: "#42, #43"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Any other relevant information"
      render: markdown
    validations:
      required: false
