name: "🎨 Pattern Implementation"
description: "Template for implementing design patterns in Project Euler solutions"
title: "🎨 [PATTERN] - Problem-<number>"
labels: [
  "pattern",
  "enhancement"
]
body:
  - type: dropdown
    id: pattern-type
    attributes:
      label: "Design Pattern"
      description: "Select the pattern to be implemented"
      options:
        - Strategy
        - Iterator
        - Observer
        - Factory Method
        - Template Method
        - Command
        - Decorator
    validations:
      required: true

  - type: input
    id: problem-number
    attributes:
      label: "Problem Number"
      description: "Project Euler problem number (3 digits)"
      placeholder: "001"
    validations:
      required: true

  - type: dropdown
    id: implementation-language
    attributes:
      label: "Primary Implementation Language"
      description: "Select the initial implementation language"
      options:
        - Python
        - Java
        - Rust
        - Haskell
        - Clojure
        - C++
    validations:
      required: true

  - type: textarea
    id: pattern-justification
    attributes:
      label: "Pattern Justification"
      description: "Why this pattern fits the problem"
      placeholder: "This pattern is suitable because..."
    validations:
      required: true

  - type: textarea
    id: implementation-plan
    attributes:
      label: "Implementation Plan"
      description: "Key components and implementation steps"
      value: |
        1. Create pattern interface/abstract class
        2. Implement concrete classes
        3. Add tests
        4. Document pattern usage
      render: markdown
    validations:
      required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: "Additional Notes"
      description: "Any other relevant information or considerations"
      render: markdown
    validations:
      required: false
